name: Prepare the release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    uses: parcelLab/ci/.github/workflows/release.yaml@v9
    secrets:
      repoAccessToken: ${{ secrets.REPO_ACCESS_TOKEN_OPEN_SOURCE }}
